package:
  name: hello-launcher
  version: "0.0.0"

source:
  path: .

build:
  # The build number should be incremented for new builds of the same version
  number: 0       # (defaults to 0)

  entry_points:
    - sayhello = hello:say_hello

  script: python setup.py install


# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  build:
    - python 3.*
    - setuptools
  run:
    - python 3.*

about:
  home: https://github.com/meawoppl/hello-launcher
  license: BSD
  summary: Demo script for the launcher.

app:
  # The command that is called to launch the app
  entry: sayhello
  # Icon file contained in the recipe
  icon: smile.png
  summary: Laucher testing.
  # If own_environment is true, installing the app through the launcher
  # will install into its own environment. The default is false.
  own_environment: true